'use client';

import { useState } from 'react';
import type { AppData } from '../../lib/planning/types';
import { supabase } from '../../lib/supabase';

export function AdminList({ title, rows, table, refresh, setToast }: { title: string; rows: { id: string; name: string; meta: string }[]; table: string; data: AppData; refresh: () => void; setToast: (value: string) => void }) {
  const [adding,setAdding]=useState(false),[name,setName]=useState(''),[editing,setEditing]=useState<{id:string;name:string}|null>(null);
  async function save(){if(!name.trim())return;const result=table==='team_members'?await supabase.from('team_members').insert({full_name:name,initials:name.split(' ').map(item=>item[0]).join('').slice(0,2).toUpperCase()}):table==='project_types'?await supabase.from('project_types').insert({name}):await supabase.from('activity_types').insert({name});if(result.error)setToast(result.error.message);else{setAdding(false);setName('');refresh();setToast(`${title.slice(0,-1)} added.`)}}
  async function saveEdit(){if(!editing?.name.trim())return;const result=table==='team_members'?await supabase.from('team_members').update({full_name:editing.name,initials:editing.name.split(' ').map(item=>item[0]).join('').slice(0,2).toUpperCase()}).eq('id',editing.id):table==='project_types'?await supabase.from('project_types').update({name:editing.name}).eq('id',editing.id):await supabase.from('activity_types').update({name:editing.name}).eq('id',editing.id);if(result.error)setToast(result.error.message);else{setEditing(null);refresh();setToast(`${title.slice(0,-1)} updated.`)}}
  async function archive(row:{id:string;name:string}){if(!confirm(`Archive ${row.name}? Existing records will keep their history, but this option will no longer appear in new forms.`))return;const result=table==='team_members'?await supabase.from('team_members').update({archived_at:new Date().toISOString(),active:false}).eq('id',row.id):table==='project_types'?await supabase.from('project_types').update({archived_at:new Date().toISOString()}).eq('id',row.id):await supabase.from('activity_types').update({archived_at:new Date().toISOString()}).eq('id',row.id);if(result.error)setToast(result.error.message);else{refresh();setToast(`${row.name} archived.`)}}
  return <section className="admin-card"><div className="section-head"><h2>{title}</h2><button onClick={()=>{setAdding(true);setEditing(null)}}>＋ Add</button></div>{adding&&<div className="inline-edit"><input autoFocus value={name} onChange={event=>setName(event.target.value)} placeholder="Name"/><button onClick={save}>Save</button><button onClick={()=>{setAdding(false);setName('')}}>Cancel</button></div>}{!adding&&!rows.length&&<p className="empty-state">No {title.toLowerCase()} yet.</p>}{rows.map(row=><div className="admin-row" key={row.id}>{editing?.id===row.id?<div className="inline-edit admin-row-edit"><input autoFocus value={editing.name} onChange={event=>setEditing({...editing,name:event.target.value})}/><button onClick={saveEdit}>Save</button><button onClick={()=>setEditing(null)}>Cancel</button></div>:<><div><strong>{row.name}</strong><small>{row.meta}</small></div><div className="row-actions"><button onClick={()=>{setEditing({id:row.id,name:row.name});setAdding(false)}}>Edit</button><button onClick={()=>archive(row)}>Archive</button></div></>}</div>)}</section>;
}
