'use client';

import type { FormEvent } from 'react';
import { useRef, useState } from 'react';
import { FormActions } from '../shared/form-actions';
import { ErrorSummary, FieldError, focusFirstInvalid, nativeFieldErrors, RequiredMark, validationProps, type FieldErrors } from '../shared/form-validation';
import { date } from '../../lib/planning/dates';
import { evaluateActivitySchedule } from '../../lib/planning/activity-schedule';
import { projectTimingDeadline } from '../../lib/planning/scheduling';
import type { Activity, ActivityLink, AppData, Dependency, ProjectTimingRule } from '../../lib/planning/types';
import { supabase } from '../../lib/supabase';
import { ActivityScheduleEditor } from './activity-schedule-editor';
import { LinkEditor } from './link-editor';
import { TeamMemberPicker } from './team-member-picker';

export function ActivityForm({ initial, initialProjectId, data, onCancel, onSaved }: { initial?: Activity; initialProjectId?: string; data: AppData; onCancel: () => void; onSaved: () => void }) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[dependencies,setDependencies]=useState<Dependency[]>(initial?.activity_dependencies||[]),[ownerIds,setOwnerIds]=useState<string[]>(initial?.activity_owners?.map(owner=>owner.team_members.id)||[]),[links,setLinks]=useState<ActivityLink[]>(initial?.activity_links||[]),[timingRule,setTimingRule]=useState<ProjectTimingRule|null>(initial?.project_timing_rule||null),[timingOffset,setTimingOffset]=useState<number|null>(initial?.project_timing_offset_days??null),[selectedProjectId,setSelectedProjectId]=useState(initial?.project_id||initialProjectId||data.projects[0]?.id||''),[activityName,setActivityName]=useState(initial?.name||''),[startDate,setStartDate]=useState(initial?.start_date||''),[dueDate,setDueDate]=useState(initial?.due_date||'');
  const [fieldErrors,setFieldErrors]=useState<FieldErrors>({});
  const [detailsOpen,setDetailsOpen]=useState(true);
  const [scheduleOpen,setScheduleOpen]=useState(false);
  const [teamOpen,setTeamOpen]=useState(false);
  const [linksOpen,setLinksOpen]=useState(false);
  const formRef=useRef<HTMLFormElement>(null);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');const nativeErrors=nativeFieldErrors(event.currentTarget);if(Object.keys(nativeErrors).length){setFieldErrors(nativeErrors);if(nativeErrors.name||nativeErrors.project)setDetailsOpen(true);if(nativeErrors.start||nativeErrors.due)setScheduleOpen(true);focusFirstInvalid(event.currentTarget,nativeErrors);return}const form=new FormData(event.currentTarget);let start=startDate,due=dueDate;if(due<start){const errors={due:'Due date must be on or after the start date.'};setFieldErrors(errors);setScheduleOpen(true);focusFirstInvalid(event.currentTarget,errors);return}setFieldErrors({});const project=data.projects.find(project=>project.id===selectedProjectId);if(!project){setError('Choose an active project.');return}const schedule=evaluateActivitySchedule({activityId:initial?.id,activityName,project,startDate:start,dueDate:due,timingRule,timingOffsetDays:timingOffset,dependencies,activities:data.activities});if(schedule.status==='conflict'){setScheduleOpen(true);setError(schedule.message);return}if(schedule.status==='adjusted'){if(!confirm(`The current schedule rules require “${activityName}” to move from ${date(start)}–${date(due)} to ${date(schedule.placement.start_date)}–${date(schedule.placement.due_date)}. Save the activity with these dates?`))return;start=schedule.placement.start_date;due=schedule.placement.due_date;setStartDate(start);setDueDate(due)}const movesProjectStart=start<project.start_date,proposedProject=movesProjectStart?{...project,start_date:start}:project;
 if(movesProjectStart&&proposedProject){const conflicts=data.activities.filter(activity=>activity.project_id===proposedProject.id&&activity.id!==initial?.id&&activity.project_timing_rule).map(activity=>evaluateActivitySchedule({activityId:activity.id,activityName:activity.name,startDate:activity.start_date,dueDate:activity.due_date,project:proposedProject,timingRule:activity.project_timing_rule!,timingOffsetDays:activity.project_timing_offset_days??null,dependencies:activity.activity_dependencies||[],activities:data.activities})).filter(result=>result.status==='conflict'||result.status==='adjusted');if(conflicts.length){setError('Moving the project start would invalidate another activity’s fixed schedule. Revise this activity’s dates or its project.');return}}
 if(movesProjectStart&&project&&!confirm(`“${String(form.get('name'))}” begins on ${date(start)}, before ${project.name}’s start date of ${date(project.start_date)}. Saving this activity will move the project start date to ${date(start)}.`))return;
 const timingAuthorizesAfterProject=timingRule==='post_project_deadline'&&timingOffset!=null&&due<=projectTimingDeadline(project,timingRule,timingOffset);if(due>project.end_date&&!timingAuthorizesAfterProject&&!confirm(`“${activityName}” falls outside ${project.name}’s operating window (${date(project.start_date)}–${date(project.end_date)}). Save this date exception?`))return;
 const validLinks=links.filter(link=>link.url.trim()).map((link,index)=>({...link,url:link.url.trim(),label:link.label.trim(),sort_order:index}));setBusy(true);const activity={id:initial?.id||null,name:activityName,project_id:selectedProjectId,activity_type_id:String(form.get('type')||'')||null,status:String(form.get('status')),priority:String(form.get('priority')),start_date:start,due_date:due,notes:String(form.get('notes')||''),allow_outside_project:due>project.end_date,adjust_project_start:movesProjectStart,project_timing_rule:timingRule,project_timing_boundary:timingRule?'end':null,project_timing_offset_days:timingRule?timingOffset:null};const result=await supabase.rpc('save_activity',{p_activity:activity,p_owner_ids:ownerIds,p_links:validLinks,p_dependencies:dependencies.map(({depends_on_activity_id,constraint_type})=>({depends_on_activity_id,constraint_type}))});setBusy(false);if(result.error)setError(result.error.message);else onSaved()}
 return <form ref={formRef} noValidate className="edit-form structured-form" onSubmit={submit}>
  <ErrorSummary errors={fieldErrors} formRef={formRef}/>
  <details className="form-disclosure" open={detailsOpen} onToggle={event=>setDetailsOpen(event.currentTarget.open)}>
   <summary>Activity details</summary>
   <fieldset className="form-section"><legend className="sr-only">Activity details</legend><p>Define the work, where it belongs, and how urgently it needs attention.</p>
    <label htmlFor="name">Activity name<RequiredMark/><input id="name" name="name" required value={activityName} onChange={event=>setActivityName(event.target.value)} {...validationProps('name',fieldErrors)}/><FieldError name="name" errors={fieldErrors}/></label>
    <div className="form-grid"><label htmlFor="project">Project<RequiredMark/><select id="project" name="project" required value={selectedProjectId} onChange={event=>setSelectedProjectId(event.target.value)} {...validationProps('project',fieldErrors)}>{data.projects.map(project=><option value={project.id} key={project.id}>{project.name}</option>)}</select><FieldError name="project" errors={fieldErrors}/></label><label htmlFor="type">Type<select id="type" name="type" defaultValue={initial?.activity_type_id}>{data.activityTypes.map(type=><option value={type.id} key={type.id}>{type.name}</option>)}</select></label><label htmlFor="status">Status<select id="status" name="status" defaultValue={initial?.status||'not_started'}><option value="not_started">Not Started</option><option value="in_progress">In Progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select></label><label htmlFor="priority">Priority<select id="priority" name="priority" defaultValue={initial?.priority||'normal'}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></div>
   </fieldset>
  </details>
  <details className="form-disclosure" open={scheduleOpen} onToggle={event=>setScheduleOpen(event.currentTarget.open)}>
   <summary>Schedule and notes</summary>
   <fieldset className="form-section"><legend className="sr-only">Dates and notes</legend><p>Set the working dates and retain the operational context needed to complete the activity.</p><div className="form-grid"><label htmlFor="start">Start date<RequiredMark/><input id="start" name="start" type="date" required value={startDate} onChange={event=>setStartDate(event.target.value)} {...validationProps('start',fieldErrors)}/><FieldError name="start" errors={fieldErrors}/></label><label htmlFor="due">Due date<RequiredMark/><input id="due" name="due" type="date" required value={dueDate} onChange={event=>setDueDate(event.target.value)} {...validationProps('due',fieldErrors)}/><FieldError name="due" errors={fieldErrors}/></label></div><label htmlFor="notes">Notes<textarea id="notes" name="notes" rows={5} defaultValue={initial?.notes}/></label></fieldset>
   <ActivityScheduleEditor initial={initial} data={data} name={activityName} projectId={selectedProjectId} startDate={startDate} dueDate={dueDate} timingRule={timingRule} timingOffsetDays={timingOffset} dependencies={dependencies} onTimingChange={(rule,offset)=>{setTimingRule(rule);setTimingOffset(offset)}} onDependenciesChange={setDependencies} onDatesChange={(start,due)=>{setStartDate(start);setDueDate(due)}}/>
  </details>
  <details className="form-disclosure" open={teamOpen} onToggle={event=>setTeamOpen(event.currentTarget.open)}><summary>Team members{ownerIds.length ? ` · ${ownerIds.length}` : ''}</summary><TeamMemberPicker members={data.members} selected={ownerIds} onChange={ids=>{setOwnerIds(ids);if(ids.length)setTeamOpen(true)}} label="Activity team members" copy="Select the team members assigned to this activity."/></details>
  <details className="form-disclosure" open={linksOpen} onToggle={event=>setLinksOpen(event.currentTarget.open)}><summary>External links{links.length ? ` · ${links.length}` : ''}</summary><LinkEditor links={links} onChange={items=>{setLinks(items);if(items.length)setLinksOpen(true)}}/></details>
  {error&&<p className="form-error" role="alert">{error}</p>}<FormActions busy={busy} onCancel={onCancel}/>
 </form>;
}
