'use client';

import type { FormEvent } from 'react';
import { useRef, useState } from 'react';
import { FormActions } from '../shared/form-actions';
import { ErrorSummary, FieldError, focusFirstInvalid, nativeFieldErrors, RequiredMark, validationProps, type FieldErrors } from '../shared/form-validation';
import { addDays, date, dayDifference } from '../../lib/planning/dates';
import { projectTimingConflict, projectTimingDeadline } from '../../lib/planning/scheduling';
import type { Activity, ActivityLink, AppData, Dependency, ProjectTimingRule } from '../../lib/planning/types';
import { supabase } from '../../lib/supabase';
import { DependencyPicker } from './dependency-picker';
import { LinkEditor } from './link-editor';
import { TeamMemberPicker } from './team-member-picker';

export function ActivityForm({ initial, initialProjectId, data, onCancel, onSaved }: { initial?: Activity; initialProjectId?: string; data: AppData; onCancel: () => void; onSaved: () => void }) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[dependencies,setDependencies]=useState<Dependency[]>(initial?.activity_dependencies||[]),[ownerIds,setOwnerIds]=useState<string[]>(initial?.activity_owners?.map(owner=>owner.team_members.id)||[]),[links,setLinks]=useState<ActivityLink[]>(initial?.activity_links||[]),[timingRule,setTimingRule]=useState<ProjectTimingRule|null>(initial?.project_timing_rule||null),[selectedProjectId,setSelectedProjectId]=useState(initial?.project_id||initialProjectId||data.projects[0]?.id||'');
  const [fieldErrors,setFieldErrors]=useState<FieldErrors>({});
  const [detailsOpen,setDetailsOpen]=useState(true);
  const [timingOpen,setTimingOpen]=useState(false);
  const [scheduleOpen,setScheduleOpen]=useState(false);
  const [teamOpen,setTeamOpen]=useState(false);
  const [linksOpen,setLinksOpen]=useState(false);
  const [dependenciesOpen,setDependenciesOpen]=useState(false);
  const formRef=useRef<HTMLFormElement>(null);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');const nativeErrors=nativeFieldErrors(event.currentTarget);if(Object.keys(nativeErrors).length){setFieldErrors(nativeErrors);if(nativeErrors.name||nativeErrors.project)setDetailsOpen(true);if(nativeErrors.project_timing_offset_days)setTimingOpen(true);if(nativeErrors.start||nativeErrors.due)setScheduleOpen(true);focusFirstInvalid(event.currentTarget,nativeErrors);return}const form=new FormData(event.currentTarget);let start=String(form.get('start')),due=String(form.get('due'));if(due<start){const errors={due:'Due date must be on or after the start date.'};setFieldErrors(errors);setScheduleOpen(true);focusFirstInvalid(event.currentTarget,errors);return}setFieldErrors({});const adjustments:string[]=[];for(const dependency of dependencies){const prerequisite=data.activities.find(activity=>activity.id===dependency.depends_on_activity_id);if(!prerequisite)continue;if(dependency.constraint_type==='finish_to_start'&&start<prerequisite.due_date){const duration=Math.max(0,dayDifference(start,due));start=prerequisite.due_date;due=addDays(start,duration);adjustments.push(`${prerequisite.name} means this activity cannot start before ${date(start)}. Preserving its current duration moves the finish date to ${date(due)}.`)}else if(dependency.constraint_type==='finish_to_finish'&&due<prerequisite.due_date){due=prerequisite.due_date;adjustments.push(`${prerequisite.name} means this activity cannot finish before ${date(due)}.`)}}const project=data.projects.find(project=>project.id===form.get('project')),movesProjectStart=!!project&&start<project.start_date,proposedProject=project&&movesProjectStart?{...project,start_date:start}:project,timingOffset=Math.max(timingRule==='post_project_deadline'?1:0,Number(form.get('project_timing_offset_days')||0));if(proposedProject&&timingRule){const conflict=projectTimingConflict(String(form.get('name')),due,proposedProject,timingRule,timingOffset);if(conflict){setError(adjustments.length?`${adjustments.join(' ')} ${conflict}`:conflict);return}}
 if(movesProjectStart&&proposedProject){const conflicts=data.activities.filter(activity=>activity.project_id===proposedProject.id&&activity.id!==initial?.id&&activity.project_timing_rule).map(activity=>projectTimingConflict(activity.name,activity.due_date,proposedProject,activity.project_timing_rule!,activity.project_timing_offset_days||0)).filter(Boolean);if(conflicts.length){setError(conflicts.join(' '));return}}
 if(adjustments.length&&!confirm(`These prerequisite dates change the activity schedule:\n\n${adjustments.join('\n')}\n\nSave the activity with these dates?`))return;
 if(movesProjectStart&&project&&!confirm(`“${String(form.get('name'))}” begins on ${date(start)}, before ${project.name}’s start date of ${date(project.start_date)}. Saving this activity will move the project start date to ${date(start)}.`))return;
 const timingAuthorizesAfterProject=!!project&&timingRule==='post_project_deadline'&&due<=projectTimingDeadline(project,timingRule,timingOffset);if(project&&due>project.end_date&&!timingAuthorizesAfterProject&&!confirm(`“${String(form.get('name'))}” falls outside ${project.name}’s operating window (${date(project.start_date)}–${date(project.end_date)}). Save this date exception?`))return;
 const validLinks=links.filter(link=>link.url.trim()).map((link,index)=>({...link,url:link.url.trim(),label:link.label.trim(),sort_order:index}));setBusy(true);const activity={id:initial?.id||null,name:String(form.get('name')),project_id:String(form.get('project')),activity_type_id:String(form.get('type')||'')||null,status:String(form.get('status')),priority:String(form.get('priority')),start_date:start,due_date:due,notes:String(form.get('notes')||''),allow_outside_project:!!project&&due>project.end_date,adjust_project_start:movesProjectStart,project_timing_rule:timingRule,project_timing_boundary:timingRule?'end':null,project_timing_offset_days:timingRule?timingOffset:null};const result=await supabase.rpc('save_activity',{p_activity:activity,p_owner_ids:ownerIds,p_links:validLinks,p_dependencies:dependencies.map(({depends_on_activity_id,constraint_type})=>({depends_on_activity_id,constraint_type}))});setBusy(false);if(result.error)setError(result.error.message);else onSaved()}
 return <form ref={formRef} noValidate className="edit-form structured-form" onSubmit={submit}>
  <ErrorSummary errors={fieldErrors} formRef={formRef}/>
  <details className="form-disclosure" open={detailsOpen} onToggle={event=>setDetailsOpen(event.currentTarget.open)}>
   <summary>Activity details</summary>
   <fieldset className="form-section"><legend className="sr-only">Activity details</legend><p>Define the work, where it belongs, and how urgently it needs attention.</p>
    <label htmlFor="name">Activity name<RequiredMark/><input id="name" name="name" required defaultValue={initial?.name} {...validationProps('name',fieldErrors)}/><FieldError name="name" errors={fieldErrors}/></label>
    <div className="form-grid"><label htmlFor="project">Project<RequiredMark/><select id="project" name="project" required value={selectedProjectId} onChange={event=>setSelectedProjectId(event.target.value)} {...validationProps('project',fieldErrors)}>{data.projects.map(project=><option value={project.id} key={project.id}>{project.name}</option>)}</select><FieldError name="project" errors={fieldErrors}/></label><label htmlFor="type">Type<select id="type" name="type" defaultValue={initial?.activity_type_id}>{data.activityTypes.map(type=><option value={type.id} key={type.id}>{type.name}</option>)}</select></label><label htmlFor="status">Status<select id="status" name="status" defaultValue={initial?.status||'not_started'}><option value="not_started">Not Started</option><option value="in_progress">In Progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select></label><label htmlFor="priority">Priority<select id="priority" name="priority" defaultValue={initial?.priority||'normal'}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></div>
   </fieldset>
  </details>
  <details className="form-disclosure" open={timingOpen} onToggle={event=>setTimingOpen(event.currentTarget.open)}>
   <summary>Project timing{timingRule ? ' · Set' : ''}</summary>
   <fieldset className="form-section"><legend className="sr-only">Project timing</legend><p>Optionally set a completion deadline relative to this project’s end date.</p><label htmlFor="timing-rule">Timing rule<select id="timing-rule" value={timingRule||''} onChange={event=>{const value=(event.target.value||null) as ProjectTimingRule|null;setTimingRule(value);if(value)setTimingOpen(true)}}><option value="">No project timing rule</option><option value="advance_deadline">Complete X days before project end date</option><option value="post_project_deadline">Complete within X days after project end date</option></select></label>{timingRule&&<label htmlFor="project_timing_offset_days">{timingRule==='advance_deadline'?'Calendar days before project end date':'Calendar days after project end date'}<RequiredMark/><input id="project_timing_offset_days" key={timingRule} name="project_timing_offset_days" type="number" min={timingRule==='post_project_deadline'?1:0} step="1" required defaultValue={initial?.project_timing_rule===timingRule?initial.project_timing_offset_days??(timingRule==='post_project_deadline'?1:0):timingRule==='post_project_deadline'?1:0} {...validationProps('project_timing_offset_days',fieldErrors)}/><FieldError name="project_timing_offset_days" errors={fieldErrors}/></label>}</fieldset>
  </details>
  <details className="form-disclosure" open={scheduleOpen} onToggle={event=>setScheduleOpen(event.currentTarget.open)}>
   <summary>Schedule and notes</summary>
   <fieldset className="form-section"><legend className="sr-only">Schedule and notes</legend><p>Set the working dates and retain the operational context needed to complete the activity.</p><div className="form-grid"><label htmlFor="start">Start date<RequiredMark/><input id="start" name="start" type="date" required defaultValue={initial?.start_date} {...validationProps('start',fieldErrors)}/><FieldError name="start" errors={fieldErrors}/></label><label htmlFor="due">Due date<RequiredMark/><input id="due" name="due" type="date" required defaultValue={initial?.due_date} {...validationProps('due',fieldErrors)}/><FieldError name="due" errors={fieldErrors}/></label></div><label htmlFor="notes">Notes<textarea id="notes" name="notes" rows={5} defaultValue={initial?.notes}/></label></fieldset>
  </details>
  <details className="form-disclosure" open={teamOpen} onToggle={event=>setTeamOpen(event.currentTarget.open)}><summary>Team members{ownerIds.length ? ` · ${ownerIds.length}` : ''}</summary><TeamMemberPicker members={data.members} selected={ownerIds} onChange={ids=>{setOwnerIds(ids);if(ids.length)setTeamOpen(true)}} label="Activity team members" copy="Select the team members assigned to this activity."/></details>
  <details className="form-disclosure" open={linksOpen} onToggle={event=>setLinksOpen(event.currentTarget.open)}><summary>External links{links.length ? ` · ${links.length}` : ''}</summary><LinkEditor links={links} onChange={items=>{setLinks(items);if(items.length)setLinksOpen(true)}}/></details>
  <details className="form-disclosure" open={dependenciesOpen} onToggle={event=>setDependenciesOpen(event.currentTarget.open)}><summary>Prerequisites{dependencies.length ? ` · ${dependencies.length}` : ''}</summary><DependencyPicker activities={data.activities} dependencies={dependencies} onChange={items=>{setDependencies(items);if(items.length)setDependenciesOpen(true)}} initialId={initial?.id}/></details>
  {error&&<p className="form-error" role="alert">{error}</p>}<FormActions busy={busy} onCancel={onCancel}/>
 </form>;
}
