'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';

type Kind='overview'|'projects'|'activities'|'administration'|'project'|'activity';
type Member={id:string;full_name:string;initials:string;email?:string;active:boolean};
type TypeRow={id:string;name:string;color:string};
type Project={id:string;name:string;description:string;status:string;start_date:string;end_date:string;project_types?:TypeRow;project_owners?:{team_members:Member}[];activities?:Activity[]};
type Activity={id:string;name:string;status:string;priority:string;start_date:string;due_date:string;notes:string;project_id:string;activity_type_id?:string;projects?:{id:string;name:string;start_date:string;end_date:string};activity_types?:TypeRow;activity_owners?:{team_members:Member}[];activity_links?:{id:string;label:string;url:string}[];activity_dependencies?:{id:string;constraint_type:string;depends_on_activity_id:string;activities?:{id:string;name:string;due_date:string}}[]};
type AppData={projects:Project[];activities:Activity[];members:Member[];projectTypes:TypeRow[];activityTypes:TypeRow[]};
const statusLabel=(v:string)=>({draft:'Draft',on_track:'On Track',at_risk:'At Risk',blocked:'Blocked',completed:'Completed',not_started:'Not Started',in_progress:'In Progress'}[v]||v);
const date=(v:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(`${v}T12:00:00`));
const fallback:AppData={
 members:[{id:'m1',full_name:'Peter Choo',initials:'PC',active:true},{id:'m2',full_name:'Mina Park',initials:'MP',active:true},{id:'m3',full_name:'Jules Lee',initials:'JL',active:true},{id:'m4',full_name:'Rina Singh',initials:'RS',active:true}],
 projectTypes:[{id:'t1',name:'Event',color:'#b59352'},{id:'t2',name:'Menu',color:'#6f4937'},{id:'t3',name:'Maintenance',color:'#58788c'},{id:'t4',name:'Marketing',color:'#7b6b8d'}],
 activityTypes:[{id:'a1',name:'Menu Development',color:'#6f4937'},{id:'a2',name:'Vendor Coordination',color:'#b59352'},{id:'a3',name:'Social Media Post',color:'#7b6b8d'},{id:'a4',name:'Facilities',color:'#58788c'}],
 projects:[
  {id:'p1',name:'Autumn Harvest Dinner',description:'A one-night dinner celebrating Catskills farms.',status:'on_track',start_date:'2026-08-24',end_date:'2026-09-14',project_types:{id:'t1',name:'Event',color:'#b59352'}},
  {id:'p2',name:'Fall Menu Launch',description:'Develop, cost, train, and launch the fall menu.',status:'at_risk',start_date:'2026-08-28',end_date:'2026-09-25',project_types:{id:'t2',name:'Menu',color:'#6f4937'}},
  {id:'p3',name:'Dining Room Lighting',description:'Replace fixtures and tune evening light levels.',status:'blocked',start_date:'2026-09-03',end_date:'2026-09-19',project_types:{id:'t3',name:'Maintenance',color:'#58788c'}},
  {id:'p4',name:'Holiday Private Events',description:'Package and promote holiday private dining.',status:'draft',start_date:'2026-09-12',end_date:'2026-10-12',project_types:{id:'t4',name:'Marketing',color:'#7b6b8d'}}],
 activities:[
  {id:'x1',project_id:'p1',name:'Confirm farm partners',status:'in_progress',priority:'high',start_date:'2026-08-24',due_date:'2026-09-02',notes:'Confirm produce quantities and delivery windows.',projects:{id:'p1',name:'Autumn Harvest Dinner',start_date:'2026-08-24',end_date:'2026-09-14'},activity_types:{id:'a2',name:'Vendor Coordination',color:'#b59352'}},
  {id:'x2',project_id:'p2',name:'Finalize fall menu costing',status:'in_progress',priority:'urgent',start_date:'2026-08-28',due_date:'2026-09-03',notes:'Review plate cost targets and final pricing.',projects:{id:'p2',name:'Fall Menu Launch',start_date:'2026-08-28',end_date:'2026-09-25'},activity_types:{id:'a1',name:'Menu Development',color:'#6f4937'}},
  {id:'x3',project_id:'p2',name:'Dessert testing',status:'blocked',priority:'high',start_date:'2026-09-01',due_date:'2026-09-05',notes:'Complete apple and black-sesame dessert trials.',projects:{id:'p2',name:'Fall Menu Launch',start_date:'2026-08-28',end_date:'2026-09-25'},activity_types:{id:'a1',name:'Menu Development',color:'#6f4937'}},
  {id:'x4',project_id:'p3',name:'Electrician site visit',status:'not_started',priority:'high',start_date:'2026-09-03',due_date:'2026-09-05',notes:'Review circuits and installation access.',projects:{id:'p3',name:'Dining Room Lighting',start_date:'2026-09-03',end_date:'2026-09-19'},activity_types:{id:'a4',name:'Facilities',color:'#58788c'}}]};

async function loadData():Promise<AppData>{
 const [p,a,m,pt,at]=await Promise.all([
  supabase.from('projects').select('*,project_types(*),project_owners(team_members(*))').is('archived_at',null).order('start_date'),
  supabase.from('activities').select('*,projects(id,name,start_date,end_date),activity_types(*),activity_owners(team_members(*)),activity_links(*),activity_dependencies(id,constraint_type,depends_on_activity_id,activities!activity_dependencies_depends_on_activity_id_fkey(id,name,due_date))').is('archived_at',null).order('due_date'),
  supabase.from('team_members').select('*').is('archived_at',null).order('full_name'),supabase.from('project_types').select('*').is('archived_at',null).order('name'),supabase.from('activity_types').select('*').is('archived_at',null).order('name')]);
 if(p.error||a.error||m.error||pt.error||at.error) throw p.error||a.error||m.error||pt.error||at.error;
 return {projects:(p.data||[]) as Project[],activities:(a.data||[]) as Activity[],members:(m.data||[]) as Member[],projectTypes:(pt.data||[]) as TypeRow[],activityTypes:(at.data||[]) as TypeRow[]};
}

export default function ThresholdApp({view,id}:{view:Kind;id?:string}){
 const [data,setData]=useState<AppData>({projects:[],activities:[],members:[],projectTypes:[],activityTypes:[]}),[loading,setLoading]=useState(true),[live,setLive]=useState(false),[query,setQuery]=useState(''),[modal,setModal]=useState<'project'|'activity'|null>(null),[toast,setToast]=useState('');
 const refresh=async()=>{try{const next=await loadData();setData(next);setLive(true)}catch{}finally{setLoading(false)}};
 useEffect(()=>{supabase.auth.getSession().then(({data:{session}})=>{if(!session){location.href='/sign-in'}else refresh()});const channel=supabase.channel('threshold-live').on('postgres_changes',{event:'*',schema:'public'},refresh).subscribe();return()=>{supabase.removeChannel(channel)}},[]);
 const selectedProject=data.projects.find(p=>p.id===id),selectedActivity=data.activities.find(a=>a.id===id);
 const title=view==='overview'?'Overview':view==='administration'?'Administration':view==='project'?(selectedProject?.name||'Project'):view==='activity'?(selectedActivity?.name||'Activity'):view[0].toUpperCase()+view.slice(1);
 return <main className="app-shell"><Sidebar view={view}/><section className="main-panel"><header className="topbar"><Link href="/" className="mobile-mark">T</Link><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this view"/></label><div className="top-actions"><span className={`live-dot ${live?'online':''}`}>{loading?'Connecting…':live?'Live':'Prototype data'}</span><button className="create-btn" onClick={()=>setModal(view==='activities'||view==='activity'?'activity':'project')}>＋ New {view==='activities'||view==='activity'?'activity':'project'}</button></div></header><div className="content">{toast&&<div className="notice" role="status"><span>{toast}</span><button onClick={()=>setToast('')}>×</button></div>}{view==='overview'&&<Overview data={data} query={query}/>} {view==='projects'&&<Projects data={data} query={query} onNew={()=>setModal('project')}/>} {view==='activities'&&<Activities data={data} query={query} onNew={()=>setModal('activity')}/>} {view==='administration'&&<Administration data={data} refresh={refresh} setToast={setToast}/>} {view==='project'&&selectedProject&&<ProjectDetail project={selectedProject} activities={data.activities.filter(a=>a.project_id===selectedProject.id)} setToast={setToast}/>} {view==='activity'&&selectedActivity&&<ActivityDetail activity={selectedActivity} data={data} refresh={refresh} setToast={setToast}/>}</div><MobileNav/></section>{modal&&<Editor kind={modal} data={data} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);refresh();setToast(`${modal==='project'?'Project':'Activity'} saved.`)}}/>}</main>
}

function Sidebar({view}:{view:Kind}){return <aside className="sidebar"><div className="brand"><img src="/threshold-logo-white.png" alt="Threshold"/><span>Projects</span></div><nav>{[['overview','/','⌂','Overview'],['projects','/projects','◇','Projects'],['activities','/activities','✓','Activities'],['administration','/administration','⚙','Administration']].map(([k,to,icon,label])=><Link key={k} href={to} className={`nav-item ${(view===k||(view==='project'&&k==='projects')||(view==='activity'&&k==='activities'))?'active':''}`}><span>{icon}</span>{label}</Link>)}</nav><div className="sidebar-foot"><div className="avatar">PC</div><div><strong>Peter Choo</strong><small>Management team</small></div><button onClick={()=>supabase.auth.signOut().then(()=>location.href='/sign-in')}>Sign out</button></div></aside>}
function MobileNav(){return <nav className="bottom-nav"><Link href="/"><span>⌂</span>Overview</Link><Link href="/projects"><span>◇</span>Projects</Link><Link href="/activities"><span>✓</span>Activities</Link><Link href="/administration"><span>•••</span>More</Link></nav>}
function Pill({value}:{value:string}){return <span className={`status-pill status-${value}`}>{statusLabel(value)}</span>}
function Heading({eyebrow,title,copy,action}:{eyebrow:string;title:string;copy:string;action?:React.ReactNode}){return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div>{action}</div>}
function Overview({data,query}:{data:AppData;query:string}){const ps=data.projects.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));const overdue=data.activities.filter(a=>a.status!=='completed'&&a.due_date<'2026-08-29').length;return <><Heading eyebrow="Saturday, August 29" title="Good morning, Peter." copy="Here’s how the work across Threshold is moving."/><section className="metric-grid"><article><div className="metric-icon overdue">!</div><div><strong>{overdue}</strong><span>Overdue activities</span></div><small>Review priority work</small></article><article><div className="metric-icon due">↗</div><div><strong>{data.activities.filter(a=>a.due_date>='2026-08-29'&&a.due_date<='2026-09-05').length}</strong><span>Due in 7 days</span></div><small>Across active projects</small></article><article><div className="metric-icon unassigned">○</div><div><strong>{data.activities.filter(a=>!a.activity_owners?.length).length}</strong><span>Unassigned</span></div><small>Ready for an owner</small></article></section><section className="portfolio-card"><div className="section-head"><div><p className="eyebrow">Portfolio timeline</p><h2>Active projects</h2></div><Link href="/projects">View all →</Link></div><div className="range-tabs"><button>Week</button><button className="selected">Month</button><button>Quarter</button><button>Half-year</button><button>Year</button></div><div className="gantt desktop-only"><div className="gantt-header"><div>Project</div><div className="weeks"><span>Aug 24</span><span>Aug 31</span><span>Sep 7</span><span>Sep 14</span><span>Sep 21</span></div></div>{ps.map((p,i)=><div className="gantt-row" key={p.id}><Link className="project-label" href={`/projects/${p.id}`}><strong>{p.name}</strong><span>{p.project_types?.name} · {progress(p,data.activities)}% complete</span></Link><div className="timeline"><div className={`bar status-${p.status}`} style={{left:`${6+i*13}%`,width:`${52-i*3}%`}}><span>{statusLabel(p.status)}</span><b style={{width:`${progress(p,data.activities)}%`}}/></div></div></div>)}</div><div className="project-cards mobile-only">{ps.map(p=><ProjectCard key={p.id} p={p} activities={data.activities}/>)}</div></section><OwnerBreakdown data={data}/></>}
const progress=(p:Project,activities:Activity[])=>{const rows=activities.filter(a=>a.project_id===p.id);return rows.length?Math.round(rows.filter(a=>a.status==='completed').length/rows.length*100):0};
function ProjectCard({p,activities}:{p:Project;activities:Activity[]}){return <Link href={`/projects/${p.id}`} className="project-tile"><div className="card-title"><div><small>{p.project_types?.name||'Project'}</small><h3>{p.name}</h3></div><Pill value={p.status}/></div><div className="date-row"><span>{date(p.start_date)}</span><i/><span>{date(p.end_date)}</span></div><div className="progress"><div><span>Activity progress</span><strong>{progress(p,activities)}%</strong></div><i><b style={{width:`${progress(p,activities)}%`}}/></i></div></Link>}
function OwnerBreakdown({data}:{data:AppData}){return <section className="breakdown overview-breakdown"><div className="section-head"><div><p className="eyebrow">Team workload</p><h2>Activity breakdown by owner</h2></div><Link href="/activities">View activities →</Link></div>{data.members.map((m,i)=><div className="owner-row" key={m.id}><span>{m.full_name.split(' ')[0]}</span><div className="stack" style={{width:`${82-i*11}%`}}><i className="not-started" style={{width:'28%'}}/><i className="in-progress" style={{width:'50%'}}/><i className="blocked" style={{width:'22%'}}/></div><strong>{data.activities.filter(a=>a.activity_owners?.some(o=>o.team_members.id===m.id)).length}</strong></div>)}</section>}
function Projects({data,query,onNew}:{data:AppData;query:string;onNew:()=>void}){const ps=data.projects.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));return <><Heading eyebrow="Planning portfolio" title="Projects" copy="Search, sort, and open every active operating window." action={<button className="secondary-btn" onClick={onNew}>＋ New project</button>}/><div className="table-card"><table><thead><tr><th>Project</th><th>Type</th><th>Status</th><th>Start</th><th>End</th><th>Progress</th><th>Owners</th></tr></thead><tbody>{ps.map(p=><tr key={p.id}><td><Link href={`/projects/${p.id}`}><strong>{p.name}</strong><small>{p.description}</small></Link></td><td>{p.project_types?.name}</td><td><Pill value={p.status}/></td><td>{date(p.start_date)}</td><td>{date(p.end_date)}</td><td>{progress(p,data.activities)}%</td><td><AvatarList owners={p.project_owners?.map(o=>o.team_members)||[]}/></td></tr>)}</tbody></table></div><div className="mobile-list">{ps.map(p=><ProjectCard key={p.id} p={p} activities={data.activities}/>)}</div></>}
function AvatarList({owners}:{owners:Member[]}){return <div className="avatars">{owners.length?owners.map(o=><span key={o.id} title={o.full_name}>{o.initials}</span>):<em>Unassigned</em>}</div>}
function Activities({data,query,onNew}:{data:AppData;query:string;onNew:()=>void}){const [status,setStatus]=useState('all'),[priority,setPriority]=useState('all');const rows=data.activities.filter(a=>(a.name+a.projects?.name).toLowerCase().includes(query.toLowerCase())&&(status==='all'||a.status===status)&&(priority==='all'||a.priority===priority));return <><Heading eyebrow="Cross-project work" title="Activities" copy="Find priorities by owner, status, type, and due date." action={<button className="secondary-btn" onClick={onNew}>＋ New activity</button>}/><div className="filters"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">All priorities</option><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select><span>{rows.length} activities</span></div><div className="table-card"><table><thead><tr><th>Activity</th><th>Project</th><th>Type</th><th>Owners</th><th>Status</th><th>Priority</th><th>Start</th><th>Due</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><Link href={`/activities/${a.id}`}><strong>{a.name}</strong></Link></td><td>{a.projects?.name}</td><td>{a.activity_types?.name}</td><td><AvatarList owners={a.activity_owners?.map(o=>o.team_members)||[]}/></td><td><Pill value={a.status}/></td><td><span className={`priority priority-${a.priority}`}>{a.priority}</span></td><td>{date(a.start_date)}</td><td>{date(a.due_date)}</td></tr>)}</tbody></table></div><div className="mobile-list">{rows.map(a=><Link className="activity-card" href={`/activities/${a.id}`} key={a.id}><small>{a.projects?.name}</small><h3>{a.name}</h3><div><Pill value={a.status}/><span className={`priority priority-${a.priority}`}>{a.priority}</span></div><p>{date(a.start_date)} — {date(a.due_date)}</p></Link>)}</div></>}
function ProjectDetail({project,activities,setToast}:{project:Project;activities:Activity[];setToast:(s:string)=>void}){return <><Heading eyebrow={project.project_types?.name||'Project'} title={project.name} copy={project.description}/><section className="detail-summary"><div><span>Status</span><Pill value={project.status}/></div><div><span>Operating window</span><strong>{date(project.start_date)} — {date(project.end_date)}</strong></div><div><span>Activity progress</span><strong>{progress(project,activities)}%</strong></div><button className="secondary-btn" onClick={()=>setToast('Project editing uses explicit Save and Cancel controls in the creation form.')}>Edit project</button></section><section className="portfolio-card"><div className="section-head"><div><p className="eyebrow">Project timeline</p><h2>Activity sequence</h2></div></div><div className="detail-timeline">{activities.map((a,i)=><div key={a.id}><Link href={`/activities/${a.id}`}>{a.name}<small>{statusLabel(a.status)}</small></Link><span><i className={`status-${a.status}`} style={{left:`${i*13}%`,width:'42%'}}/></span></div>)}</div></section><Activities data={{...fallback,activities,projects:[project]}} query="" onNew={()=>setToast('Use “New activity” in the top bar to add work to this project.')}/></>}
function ActivityDetail({activity,data,refresh,setToast}:{activity:Activity;data:AppData;refresh:()=>void;setToast:(s:string)=>void}){const [edit,setEdit]=useState(false);return <><Heading eyebrow={activity.projects?.name||'Activity'} title={activity.name} copy="Activity detail, schedule context, and dependencies."/><section className="focus-timeline"><p className="eyebrow">Schedule context</p><div><strong>{activity.projects?.name}</strong><i className="project-line"/></div><div><strong>{activity.name}</strong><i className={`activity-line status-${activity.status}`}/></div></section>{edit?<ActivityForm initial={activity} data={data} onCancel={()=>setEdit(false)} onSaved={()=>{setEdit(false);refresh();setToast('Activity changes saved.')}}/>:<section className="activity-detail"><div className="detail-actions"><Pill value={activity.status}/><button className="secondary-btn" onClick={()=>setEdit(true)}>Edit activity</button></div><div className="detail-grid"><div><span>Type</span><strong>{activity.activity_types?.name||'—'}</strong></div><div><span>Priority</span><strong>{statusLabel(activity.priority)}</strong></div><div><span>Start</span><strong>{date(activity.start_date)}</strong></div><div><span>Due</span><strong>{date(activity.due_date)}</strong></div><div><span>Owners</span><AvatarList owners={activity.activity_owners?.map(o=>o.team_members)||[]}/></div></div><article><h2>Notes</h2><p>{activity.notes||'No notes added.'}</p></article><article><h2>Prerequisites</h2>{activity.activity_dependencies?.length?activity.activity_dependencies.map(d=><Link key={d.id} href={`/activities/${d.depends_on_activity_id}`}>{d.activities?.name} · {statusLabel(d.constraint_type)}</Link>):<p>No prerequisites assigned.</p>}</article><article><h2>External links</h2>{activity.activity_links?.length?activity.activity_links.map(l=><a key={l.id} href={l.url} target="_blank" rel="noreferrer">{l.label||l.url} ↗</a>):<p>No links added.</p>}</article></section>}</>}
function Administration({data,refresh,setToast}:{data:AppData;refresh:()=>void;setToast:(s:string)=>void}){return <><Heading eyebrow="Workspace settings" title="Administration" copy="Manage the shared team directory and planning vocabulary."/><div className="admin-grid"><AdminList title="Team members" rows={data.members.map(x=>({id:x.id,name:x.full_name,meta:x.email||x.initials}))} table="team_members" data={data} refresh={refresh} setToast={setToast}/><AdminList title="Project types" rows={data.projectTypes.map(x=>({id:x.id,name:x.name,meta:'Project type'}))} table="project_types" data={data} refresh={refresh} setToast={setToast}/><AdminList title="Activity types" rows={data.activityTypes.map(x=>({id:x.id,name:x.name,meta:'Activity type'}))} table="activity_types" data={data} refresh={refresh} setToast={setToast}/></div></>}
function AdminList({title,rows,table,refresh,setToast}:{title:string;rows:{id:string;name:string;meta:string}[];table:string;data:AppData;refresh:()=>void;setToast:(s:string)=>void}){const [adding,setAdding]=useState(false),[name,setName]=useState('');async function save(){if(!name.trim())return;const result=table==='team_members'?await supabase.from('team_members').insert({full_name:name,initials:name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}):table==='project_types'?await supabase.from('project_types').insert({name}):await supabase.from('activity_types').insert({name});if(result.error)setToast(result.error.message);else{setAdding(false);setName('');refresh();setToast(`${title.slice(0,-1)} added.`)}}return <section className="admin-card"><div className="section-head"><h2>{title}</h2><button onClick={()=>setAdding(true)}>＋ Add</button></div>{adding&&<div className="inline-edit"><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Name"/><button onClick={save}>Save</button><button onClick={()=>setAdding(false)}>Cancel</button></div>}{rows.map(r=><div className="admin-row" key={r.id}><div><strong>{r.name}</strong><small>{r.meta}</small></div><button onClick={()=>setToast(`${r.name} is active. Archive controls preserve existing records.`)}>•••</button></div>)}</section>}
function Editor({kind,data,onClose,onSaved}:{kind:'project'|'activity';data:AppData;onClose:()=>void;onSaved:()=>void}){return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={onClose}>×</button><p className="eyebrow">Create new</p><h1>{kind==='project'?'Project':'Activity'}</h1>{kind==='activity'?<ActivityForm data={data} onCancel={onClose} onSaved={onSaved}/>:<ProjectForm data={data} onCancel={onClose} onSaved={onSaved}/>}</div></div>}
function ProjectForm({data,onCancel,onSaved}:{data:AppData;onCancel:()=>void;onSaved:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const {error}=await supabase.from('projects').insert({name:f.get('name'),description:f.get('description'),project_type_id:f.get('type')||null,status:f.get('status'),start_date:f.get('start'),end_date:f.get('end')});setBusy(false);if(error)setError(error.message);else onSaved()}return <form className="edit-form" onSubmit={submit}><label>Name<input name="name" required/></label><label>Description<textarea name="description" rows={3}/></label><div className="form-grid"><label>Type<select name="type">{data.projectTypes.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Status<select name="status"><option value="draft">Draft</option><option value="on_track">On Track</option><option value="at_risk">At Risk</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select></label><label>Start date<input name="start" type="date" required/></label><label>End date<input name="end" type="date" required/></label></div>{error&&<p className="form-error">{error}</p>}<FormActions busy={busy} onCancel={onCancel}/></form>}
function ActivityForm({initial,data,onCancel,onSaved}:{initial?:Activity;data:AppData;onCancel:()=>void;onSaved:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),start=String(f.get('start')),due=String(f.get('due')),project=data.projects.find(p=>p.id===f.get('project'));if(due<start){setError('Due date must be on or after the start date.');return}if(project&&(start<project.start_date||due>project.end_date)&&!confirm(`This activity falls outside ${project.name}’s operating window. Save this exception?`))return;setBusy(true);const payload={name:f.get('name'),project_id:f.get('project'),activity_type_id:f.get('type')||null,status:f.get('status'),priority:f.get('priority'),start_date:start,due_date:due,notes:f.get('notes'),allow_outside_project:!!project&&(start<project.start_date||due>project.end_date)};const result=initial?await supabase.from('activities').update(payload).eq('id',initial.id):await supabase.from('activities').insert(payload);setBusy(false);if(result.error)setError(result.error.message);else onSaved()}return <form className="edit-form" onSubmit={submit}><label>Activity name<input name="name" required defaultValue={initial?.name}/></label><div className="form-grid"><label>Project<select name="project" defaultValue={initial?.project_id}>{data.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Type<select name="type" defaultValue={initial?.activity_type_id}>{data.activityTypes.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Status<select name="status" defaultValue={initial?.status||'not_started'}><option value="not_started">Not Started</option><option value="in_progress">In Progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select></label><label>Priority<select name="priority" defaultValue={initial?.priority||'normal'}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label>Start date<input name="start" type="date" required defaultValue={initial?.start_date}/></label><label>Due date<input name="due" type="date" required defaultValue={initial?.due_date}/></label></div><label>Notes<textarea name="notes" rows={5} defaultValue={initial?.notes}/></label>{error&&<p className="form-error">{error}</p>}<FormActions busy={busy} onCancel={onCancel}/></form>}
function FormActions({busy,onCancel}:{busy:boolean;onCancel:()=>void}){return <div className="form-actions"><button type="button" className="secondary-btn" onClick={onCancel}>Cancel</button><button className="create-btn" disabled={busy}>{busy?'Saving…':'Save'}</button></div>}
