'use client';

import type { FormEvent } from 'react';
import { useState } from 'react';
import { FormActions } from '../shared/form-actions';
import { date } from '../../lib/planning/dates';
import { projectTimingConflict } from '../../lib/planning/scheduling';
import type { AppData, Project } from '../../lib/planning/types';
import { supabase } from '../../lib/supabase';
import { TeamMemberPicker } from '../activities/team-member-picker';

export function ProjectForm({ initial, data, onCancel, onSaved }: { initial?: Project; data: AppData; onCancel: () => void; onSaved: () => void }) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[ownerIds,setOwnerIds]=useState<string[]>(initial?.project_owners?.map(owner=>owner.team_members.id)||[]);
  async function submit(event: FormEvent<HTMLFormElement>) {event.preventDefault();setError('');const form=new FormData(event.currentTarget),start=String(form.get('start')),end=String(form.get('end'));if(end<start){setError('End date must be on or after the start date.');return}const proposed={...(initial||{}),id:initial?.id||'',name:String(form.get('name')),description:String(form.get('description')||''),status:String(form.get('status')),start_date:start,end_date:end} as Project;if(initial){const earliestActivity=data.activities.filter(activity=>activity.project_id===initial.id).sort((left,right)=>left.start_date.localeCompare(right.start_date))[0];if(earliestActivity&&start>earliestActivity.start_date){setError(`Project start cannot move to ${date(start)} because “${earliestActivity.name}” begins on ${date(earliestActivity.start_date)}.`);return}const conflicts=data.activities.filter(activity=>activity.project_id===initial.id&&activity.project_timing_rule).map(activity=>projectTimingConflict(activity.name,activity.due_date,proposed,activity.project_timing_rule!,activity.project_timing_offset_days||0)).filter(Boolean);if(conflicts.length){setError(conflicts.join(' '));return}}setBusy(true);const project={id:initial?.id||null,name:String(form.get('name')),description:String(form.get('description')||''),project_type_id:String(form.get('type')||'')||null,status:String(form.get('status')),start_date:start,end_date:end};const result=await supabase.rpc('save_project',{p_project:project,p_owner_ids:ownerIds});setBusy(false);if(result.error)setError(result.error.message);else onSaved()}
  return <form className="edit-form structured-form" onSubmit={submit}><fieldset className="form-section"><legend>Project brief</legend><p>Name the operating window and capture the concise brief people need to understand it.</p><label>Name<input name="name" required defaultValue={initial?.name}/></label><label>Description<textarea name="description" rows={3} defaultValue={initial?.description}/></label></fieldset><fieldset className="form-section"><legend>Classification and schedule</legend><p>Set the planning vocabulary, current health, and intentional project window.</p><div className="form-grid"><label>Type<select name="type" defaultValue={initial?.project_type_id||initial?.project_types?.id}>{data.projectTypes.map(type=><option value={type.id} key={type.id}>{type.name}</option>)}</select></label><label>Status<select name="status" defaultValue={initial?.status||'draft'}><option value="draft">Draft</option><option value="on_track">On Track</option><option value="at_risk">At Risk</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select></label><label>Start date<input name="start" type="date" required defaultValue={initial?.start_date}/></label><label>End date<input name="end" type="date" required defaultValue={initial?.end_date}/></label></div></fieldset><TeamMemberPicker members={data.members} selected={ownerIds} onChange={setOwnerIds} label="Project team members" copy="Select the team members assigned to this project."/>{error&&<p className="form-error" role="alert">{error}</p>}<FormActions busy={busy} onCancel={onCancel}/></form>;
}
