'use client';

import { useState } from 'react';
import { ActivityPanel } from '../activities/activity-panel';
import { Heading } from '../shared/page-heading';
import { Pill, statusLabel } from '../shared/status-pill';
import { date } from '../../lib/planning/dates';
import type { Activity, AppData, Project } from '../../lib/planning/types';
import { supabase } from '../../lib/supabase';
import { ProjectActivityList } from './project-activity-list';
import { ProjectForm } from './project-form';

export function ProjectDetail({ project, activities, data, refresh, setToast, onNewActivity }: { project: Project; activities: Activity[]; data: AppData; refresh: () => void; setToast: (value: string) => void; onNewActivity: () => void }) {
  const [edit,setEdit]=useState(false),[editingActivity,setEditingActivity]=useState<Activity|null>(null);
  const ordered=[...activities].sort((a,b)=>a.due_date.localeCompare(b.due_date)),next=ordered.find(a=>a.status!=='completed'),blocked=activities.filter(a=>a.status==='blocked').length,unassigned=activities.filter(a=>!a.activity_owners?.length).length,dependencyCount=activities.reduce((total,a)=>total+(a.activity_dependencies?.length||0),0);
  async function archiveProject(){if(!confirm(`Archive ${project.name} and all of its activities? The records will remain available through archived views.`))return;const result=await supabase.rpc('archive_project',{p_project_id:project.id});if(result.error)setToast(result.error.message);else location.href='/projects'}
  return <>{edit?<><Heading eyebrow="Project settings" title={`Edit ${project.name}`} copy="Update the project details, then save or cancel your changes."/><ProjectForm initial={project} data={data} onCancel={()=>setEdit(false)} onSaved={()=>{setEdit(false);refresh();setToast('Project changes saved.')}}/></>:<><Heading eyebrow={`${project.project_types?.name||'Project'} · Active project`} title={project.name} copy={project.description||'No project brief has been added yet.'} action={<div className="heading-actions"><button className="secondary-btn" onClick={()=>setEdit(true)}>Edit project</button><button className="danger-btn" onClick={archiveProject}>Archive</button></div>}/><section className="detail-summary project-summary"><div><span>Status</span><Pill value={project.status}/></div><div><span>Operating window</span><strong>{date(project.start_date)} — {date(project.end_date)}</strong></div><div><span>Activity progress</span><strong>{activities.filter(a=>a.status==='completed').length} of {activities.length} complete</strong></div><div><span>Next due</span><strong>{next?`${date(next.due_date)} · ${next.name}`:'No open activities'}</strong></div></section><div className="project-workspace"><section className="portfolio-card"><div className="section-head"><div><p className="eyebrow">Schedule</p><h2>Activity sequence</h2></div><button onClick={onNewActivity}>＋ New activity</button></div>{ordered.length?<div className="detail-timeline">{ordered.map((activity,i)=><div key={activity.id}><button type="button" onClick={()=>setEditingActivity(activity)}>{activity.name}<small>{statusLabel(activity.status)} · due {date(activity.due_date)}</small></button><span><i className={`status-${activity.status}`} style={{left:`${Math.min(i*11,72)}%`,width:`${Math.max(18,42-i*2)}%`}}/></span></div>)}</div>:<div className="empty-project"><strong>No activities yet</strong><p>Add the first activity to begin shaping this project’s operating plan.</p><button className="create-btn" onClick={onNewActivity}>＋ New activity</button></div>}</section><aside className="decision-panel"><div><p className="eyebrow">Attention</p><h2>What needs a decision</h2></div><DecisionRow value={blocked} label="Blocked activities" copy={blocked?'Review the cause and unblock the next handoff.':'No work is currently blocked.'}/><DecisionRow value={unassigned} label="Unassigned activities" copy={unassigned?'Assign accountability before work begins.':'Every activity has a team member.'}/><DecisionRow value={dependencyCount} label="Prerequisite links" copy={dependencyCount?'Dependencies are shaping this schedule.':'No prerequisite relationships yet.'}/></aside></div><ProjectActivityList activities={ordered} onNew={onNewActivity} onEdit={setEditingActivity}/></>}{editingActivity&&<ActivityPanel activity={editingActivity} data={data} onClose={()=>setEditingActivity(null)} onSaved={()=>{setEditingActivity(null);refresh();setToast('Activity changes saved.')}}/>}</>;
}

function DecisionRow({ value, label, copy }: { value: number; label: string; copy: string }) {
  return <div className={`decision-row ${value?'needs-attention':''}`}><strong>{value}</strong><div><b>{label}</b><p>{copy}</p></div></div>;
}
